workflows:
  iOS-build:
    name: iOS Build Workflow
    environment:
      xcode: latest

    scripts:
      - wget https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_osx.universal.zip
      - unzip Godot_v3.5.3-stable_osx.universal.zip -d godot
      - sudo mv godot/Godot.app /Applications/Godot.app
      - sudo ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot
      - mkdir -p ~/Library/Application\ Support/Godot/templates/3.5.3.stable
      - ls
      - cd ~/Library/Application\ Support/Godot/templates/3.5.3.stable
      - ls
      - wget https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
      - tar -xzf Godot_v3.5.3-stable_export_templates.tpz -C ~/Library/Application\ Support/Godot/templates/3.5.3.stable
      - cd ~/Library/Application\ Support/Godot/templates/3.5.3.stable/templates
      - ls
      - mv * ..
      - cd ..
      - mkdir -p build
      - godot --export "iOS" build/your_project_name.xcodeproj
      - sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' build/your_project_name.xcodeproj/project.pbxproj
      - xcodebuild -project build/your_project_name.xcodeproj -scheme your_project_name -configuration Release -archivePath build/your_project_name.xcarchive archive \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - xcodebuild -exportArchive -archivePath build/your_project_name.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/your_project_name.ipa
