version: 2.1

jobs:
  build:
    macos:
      xcode: "13.2.1"
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Download Godot
          command: |
            wget https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_osx.universal.zip
            unzip Godot_v3.5.3-stable_osx.universal.zip -d godot
            sudo mv godot/Godot.app /Applications/Godot.app
            sudo ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot
      - run:
          name: Download Godot Export Templates
          command: |
            wget https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
            mkdir -p ~/Library/Application\ Support/Godot/templates/3.5.3.stable
            tar -xzf Godot_v3.5.3-stable_export_templates.tpz -C ~/Library/Application\ Support/Godot/templates/3.5.3.stable
      - run:
          name: Create build directory
          command: mkdir -p build
      - run:
          name: Export iOS project
          command: |
            godot --export "iOS" build/your_project_name.xcodeproj
          environment:
            DISPLAY: ":99.0"
      - run:
          name: Set iOS Deployment Target
          command: |
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' build/your_project_name.xcodeproj/project.pbxproj
      - run:
          name: Build iOS project
          command: |
            xcodebuild -project build/your_project_name.xcodeproj -scheme your_project_name -configuration Release -archivePath build/your_project_name.xcarchive archive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - run:
          name: Export IPA
          command: |
            xcodebuild -exportArchive -archivePath build/your_project_name.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - store_artifacts:
          path: build/your_project_name.ipa
          destination: output

workflows:
  version: 2
  build:
    jobs:
      - build
