name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Godot
      uses: abarichello/godot-ci@3.5.3
      with:
        godot_version: '3.5.3'
        export_templates_version: '3.5.3'

    - name: Install Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app

    - name: Create build directory
      run: mkdir -p build

    - name: Export iOS project
      run: godot --export "iOS" build/your_project_name.xcodeproj
      env:
        DISPLAY: :99.0

    - name: Build iOS project
      run: xcodebuild -project build/your_project_name.xcodeproj -scheme your_project_name -configuration Release -archivePath build/your_project_name.xcarchive archive

    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath build/your_project_name.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist

    - name: Upload IPA to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: your_project_name.ipa
        path: build/your_project_name.ipa
